# Methods and Analysis
::: {.noteblock data-latex=""}
All the source code of the `R` scripts utilized in this project is available on the project's [GitHub repository](https://github.com/AzKurban-edX-DS/Capstone-MovieLens/tree/main/r)[@edx_capstone_movielens]. 
:::

## Preparing train and set datasets
\

We will split the `edx` dataset into a training set, which we will use to build and train our models, and a test set in which we will compute the accuracy of our predictions, the way described in [Section 24.1 *Case study: recommendation systems*](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/regularization.html#sec-recommendation-systems) of the _Course Textbook (New Edition)_ mentioned above[@IDS2_24-1].We will also use the *K-Fold Cross-Validation* method as described in [Section 30.6 *Cross validation*](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/resampling-methods.html#cross-validation) of the _Course Textbook (New Edition)_[@IDS2_30-6].

To prepare datasets for processing, we will use the following functions (described in detail in the [Initializing Input Datasets] section of the [Appendix A: Support Functions] of *This Report*), specifically designed for these operations:

  - [make_source_datasets](#func.make_source_datasets);
  
  - [init_source_datasets](#func.init_source_datasets).

As a result of executing these functions, we will obtain the following datasets (detailed in [Appendix B: Models Training Datasets]), which we will use throughout *This Project*:

  - [`edx.mx` Matrix Object](#appndx_b.edx.mx): The `edx` dataset converted to a matrix;
  
  - [`edx.sgr` Object](#appndx_b.edx.sgr): A dataset derived from the `edx` by splitting each row corresponding to a movie belonging to multiple genres;

  - [`movie_map` Object](#appndx_b.movie_map): A map establishing a one-to-one correspondence between a movie ID and its title.;
  
  - [`date_days_map` Object](#appndx_b.date_days_map): A map between the rating date and the number of days since the earliest entry in the edx dataset;

  - [`edx_CV` Object](#appndx_b.edx_CV): A list of objects created from samples made from the `edx` dataset to use them for the *K-Fold Cross-Validation* in the way explained in [Section 30.6 *Cross validation / K-fold cross validation*](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/resampling-methods.html#k-fold-cross-validation) of the _Course Textbook (New Edition)_[@IDS2_30-6].


::: {.noteblock data-latex=""}
The `K` value for the *K-Fold Cross-Validation* we use in *This Project* is determined by the length of the list composing the [`edx_CV` Object]. In our case, the length of the `edx_CV` is 5, meaning we use *5-Fold Cross-Validation*.
:::

